<?php

namespace Database\Seeders;

use App\Models\NavigationMenu;
use Illuminate\Database\Seeder;

class NavigationMenuSeeder extends Seeder
{
    public function run(): void
    {
        $menus = [
            [
                'id' => 1,
                'parent_id' => null,
                'label' => 'Dashboard',
                'label_en' => 'Dashboard',
                'label_th' => 'แดชบอร์ด',
                'icon' => 'home',
                'route' => '/dashboard',
                'permission' => null,
                'sort_order' => 1,
            ],
            [
                'id' => 10,
                'parent_id' => null,
                'label' => 'Repair Request',
                'label_en' => 'Repair Request',
                'label_th' => 'งานแจ้งซ่อม',
                'icon' => 'wrench',
                'route' => null,
                'permission' => null,
                'sort_order' => 2,
            ],
            [
                'id' => 19,
                'parent_id' => 10,
                'label' => 'My Repair Jobs',
                'label_en' => 'My Repair Jobs',
                'label_th' => 'งานซ่อมของฉัน',
                'icon' => 'user',
                'route' => '/repair-requests/my-jobs',
                'permission' => 'manage_settings',
                'sort_order' => 1,
            ],
            [
                'id' => 20,
                'parent_id' => 10,
                'label' => 'Report Repair',
                'label_en' => 'Report Repair',
                'label_th' => 'แจ้งซ่อม',
                'icon' => 'wrench',
                'route' => '/repair-requests',
                'permission' => null,
                'sort_order' => 2,
            ],
            [
                'id' => 32,
                'parent_id' => 10,
                'label' => 'My Approvals',
                'label_en' => 'My Approvals',
                'label_th' => 'รายการรออนุมัติของฉัน',
                'icon' => 'clipboard-document-check',
                'route' => '/approvals/my',
                'permission' => 'approval.approve',
                'sort_order' => 3,
            ],
            [
                'id' => 21,
                'parent_id' => 10,
                'label' => 'Assign Repair Jobs',
                'label_en' => 'Assign Repair Jobs',
                'label_th' => 'แจกงานซ่อม',
                'icon' => 'users',
                'route' => '/repair-requests/assign',
                'permission' => 'manage_settings',
                'sort_order' => 4,
            ],
            [
                'id' => 22,
                'parent_id' => 10,
                'label' => 'Evaluate Repair Jobs',
                'label_en' => 'Evaluate Repair Jobs',
                'label_th' => 'ประเมินงานซ่อม',
                'icon' => 'clipboard-document-check',
                'route' => '/repair-requests/evaluate',
                'permission' => 'manage_settings',
                'sort_order' => 5,
            ],
            [
                'id' => 16,
                'parent_id' => null,
                'label' => 'Maintenance',
                'label_en' => 'Maintenance',
                'label_th' => 'งานบำรุงรักษา',
                'icon' => 'clipboard-document-check',
                'route' => null,
                'permission' => null,
                'sort_order' => 3,
            ],
            [
                'id' => 24,
                'parent_id' => 16,
                'label' => 'Create PM/AM Plan',
                'label_en' => 'Create PM/AM Work Plan',
                'label_th' => 'สร้างแผนงาน PM/AM',
                'icon' => 'document',
                'route' => '/maintenance/create-plan',
                'permission' => 'manage_settings',
                'sort_order' => 1,
            ],
            [
                'id' => 25,
                'parent_id' => 16,
                'label' => 'Auto Assign Settings',
                'label_en' => 'Set Auto Assignment',
                'label_th' => 'ตั้งค่าแจกงานอัตโนมัติ',
                'icon' => 'settings',
                'route' => '/maintenance/auto-assign',
                'permission' => 'manage_settings',
                'sort_order' => 2,
            ],
            [
                'id' => 17,
                'parent_id' => null,
                'label' => 'Reports',
                'label_en' => 'Reports',
                'label_th' => 'รายงาน',
                'icon' => 'chart-bar',
                'route' => null,
                'permission' => null,
                'sort_order' => 4,
            ],
            [
                'id' => 26,
                'parent_id' => null,
                'label' => 'Spare Parts',
                'label_en' => 'Spare Parts',
                'label_th' => 'งานอะไหล่',
                'icon' => 'cube',
                'route' => null,
                'permission' => null,
                'sort_order' => 5,
            ],
            [
                'id' => 27,
                'parent_id' => 26,
                'label' => 'Spare Parts Stock',
                'label_en' => 'Spare Parts Stock',
                'label_th' => 'สต๊อกอะไหล่',
                'icon' => 'cube',
                'route' => '/spare-parts/stock',
                'permission' => 'manage_settings',
                'sort_order' => 1,
            ],
            [
                'id' => 28,
                'parent_id' => 26,
                'label' => 'Spare Parts Withdrawal History',
                'label_en' => 'Spare Parts Withdrawal History',
                'label_th' => 'ประวัติการเบิกอะไหล่',
                'icon' => 'clock',
                'route' => '/spare-parts/withdrawal-history',
                'permission' => 'manage_settings',
                'sort_order' => 2,
            ],
            [
                'id' => 29,
                'parent_id' => null,
                'label' => 'Equipment Registry',
                'label_en' => 'Equipment / Machinery Registry',
                'label_th' => 'งานทะเบียน/อุปกรณ์/เครื่องจักร',
                'icon' => 'building-office',
                'route' => null,
                'permission' => null,
                'sort_order' => 6,
            ],
            [
                'id' => 30,
                'parent_id' => 29,
                'label' => 'Equipment List',
                'label_en' => 'Equipment / Machinery List',
                'label_th' => 'รายชื่ออุปกรณ์/เครื่องจักร',
                'icon' => 'document',
                'route' => '/equipment-registry',
                'permission' => 'manage_settings',
                'sort_order' => 1,
            ],
            [
                'id' => 35,
                'parent_id' => 29,
                'label' => 'Equipment Machinery Locations',
                'label_en' => 'Locations (Equipment/Machinery)',
                'label_th' => 'สถานที่ตั้ง อุปกรณ์/เครื่องจักร',
                'icon' => 'map-pin',
                'route' => '/equipment-locations',
                'permission' => 'manage_settings',
                'sort_order' => 2,
            ],
            [
                'id' => 23,
                'parent_id' => 17,
                'label' => 'Repair History Report',
                'label_en' => 'Repair History Report',
                'label_th' => 'รายงานประวัติการซ่อม',
                'icon' => 'chart-bar',
                'route' => '/reports/repair-history',
                'permission' => 'manage_settings',
                'sort_order' => 1,
            ],
            [
                'id' => 31,
                'parent_id' => 17,
                'label' => 'PM/AM History Report',
                'label_en' => 'PM/AM History Report',
                'label_th' => 'รายงานประวัติ PM/AM',
                'icon' => 'clipboard-document-check',
                'route' => '/reports/pm-am-history',
                'permission' => 'manage_settings',
                'sort_order' => 2,
            ],
            [
                'id' => 2,
                'parent_id' => null,
                'label' => 'Settings',
                'label_en' => 'Settings',
                'label_th' => 'ตั้งค่า',
                'icon' => 'settings',
                'route' => null,
                'permission' => null,
                'sort_order' => 7,
            ],
            /*
             * Settings children (parent_id=2): sort_order groups — org (1–2), IAM (3–7),
             * UI (8–9), workflow (10–12), equipment (13–15), audit (16). Re-seed after edits.
             */
            [
                'id' => 3,
                'parent_id' => 2,
                'label' => 'Users',
                'label_en' => 'Users',
                'label_th' => 'ผู้ใช้งาน',
                'icon' => 'users',
                'route' => '/users',
                'permission' => 'user_access.read',
                'sort_order' => 3,
            ],
            [
                'id' => 4,
                'parent_id' => 2,
                'label' => 'Roles',
                'label_en' => 'Roles',
                'label_th' => 'บทบาท',
                'icon' => 'shield',
                'route' => '/roles',
                'permission' => 'role_access.read',
                'sort_order' => 4,
            ],
            [
                'id' => 5,
                'parent_id' => 2,
                'label' => 'Permissions',
                'label_en' => 'Permissions',
                'label_th' => 'สิทธิ์การเข้าถึง',
                'icon' => 'key',
                'route' => '/permissions',
                'permission' => 'permission_access.read',
                'sort_order' => 5,
            ],
            [
                'id' => 6,
                'parent_id' => 2,
                'label' => 'Password Policy',
                'label_en' => 'Password Policy',
                'label_th' => 'นโยบายรหัสผ่าน',
                'icon' => 'lock-closed',
                'route' => '/settings/password-policy',
                'permission' => 'user_access.update',
                'sort_order' => 6,
            ],
            [
                'id' => 7,
                'parent_id' => 2,
                'label' => 'Menu Manager',
                'label_en' => 'Menu Manager',
                'label_th' => 'จัดการเมนู',
                'icon' => 'bars-3',
                'route' => '/settings/navigation',
                'permission' => 'manage_settings',
                'sort_order' => 9,
            ],
            [
                'id' => 8,
                'parent_id' => 2,
                'label' => 'Companies',
                'label_en' => 'Companies',
                'label_th' => 'บริษัท',
                'icon' => 'building-office',
                'route' => '/companies',
                'permission' => 'manage companies',
                'sort_order' => 1,
            ],
            [
                'id' => 9,
                'parent_id' => 2,
                'label' => 'Branding',
                'label_en' => 'Logo & Background',
                'label_th' => 'โลโก้และพื้นหลัง',
                'icon' => 'document',
                'route' => '/settings/branding',
                'permission' => 'manage_settings',
                'sort_order' => 8,
            ],
            [
                'id' => 11,
                'parent_id' => 2,
                'label' => 'Departments',
                'label_en' => 'Departments',
                'label_th' => 'ฝ่าย/แผนก',
                'icon' => 'building-office',
                'route' => '/settings/departments',
                'permission' => 'manage_settings',
                'sort_order' => 2,
            ],
            [
                'id' => 37,
                'parent_id' => 2,
                'label' => 'Department workflow bindings',
                'label_en' => 'Dept ↔ workflow',
                'label_th' => 'แผนก ↔ workflow',
                'icon' => 'link',
                'route' => '/settings/department-workflow-bindings',
                'permission' => 'manage_settings',
                'sort_order' => 2,
            ],
            [
                'id' => 38,
                'parent_id' => 2,
                'label' => 'Positions',
                'label_en' => 'Positions',
                'label_th' => 'ตำแหน่ง',
                'icon' => 'briefcase',
                'route' => '/settings/positions',
                'permission' => 'manage_settings',
                'sort_order' => 2,
            ],
            [
                'id' => 12,
                'parent_id' => 2,
                'label' => 'Workflow',
                'label_en' => 'Workflow',
                'label_th' => 'Workflow',
                'icon' => 'chart-bar',
                'route' => '/settings/workflow',
                'permission' => 'manage_settings',
                'sort_order' => 10,
            ],
            [
                'id' => 34,
                'parent_id' => 2,
                'label' => 'Approval Routing',
                'label_en' => 'Approval routing',
                'label_th' => 'การเลือก workflow อนุมัติ',
                'icon' => 'currency',
                'route' => '/settings/approval-routing',
                'permission' => 'manage_settings',
                'sort_order' => 11,
            ],
            [
                'id' => 33,
                'parent_id' => 2,
                'label' => 'Document Forms',
                'label_en' => 'Document Forms',
                'label_th' => 'ตั้งค่าฟอร์มเอกสาร',
                'icon' => 'document',
                'route' => '/settings/document-forms',
                'permission' => 'manage_settings',
                'sort_order' => 12,
            ],
            [
                'id' => 13,
                'parent_id' => 2,
                'label' => 'Equipment',
                'label_en' => 'Equipment / Machinery',
                'label_th' => 'อุปกรณ์/เครื่องจักร',
                'icon' => 'cube',
                'route' => '/settings/equipment',
                'permission' => 'manage_settings',
                'sort_order' => 13,
            ],
            [
                'id' => 14,
                'parent_id' => 2,
                'label' => 'Notifications',
                'label_en' => 'Notifications',
                'label_th' => 'การแจ้งเตือน',
                'icon' => 'bell',
                'route' => '/settings/notifications',
                'permission' => 'manage_settings',
                'sort_order' => 15,
            ],
            [
                'id' => 15,
                'parent_id' => 2,
                'label' => 'Equipment Locations',
                'label_en' => 'Locations (Equipment/Machinery)',
                'label_th' => 'สถานที่ตั้ง อุปกรณ์/เครื่องจักร',
                'icon' => 'map-pin',
                'route' => '/settings/equipment-locations',
                'permission' => 'manage_settings',
                'sort_order' => 14,
            ],
            [
                'id' => 36,
                'parent_id' => 2,
                'label' => 'Authentication & SSO',
                'label_en' => 'Authentication & SSO',
                'label_th' => 'การยืนยันตัวตนและ SSO',
                'icon' => 'shield-check',
                'route' => '/settings/authentication',
                'permission' => 'manage_settings',
                'sort_order' => 7,
            ],
            [
                'id' => 18,
                'parent_id' => 2,
                'label' => 'Activity History',
                'label_en' => 'Activity History',
                'label_th' => 'ประวัติการใช้งาน',
                'icon' => 'clock',
                'route' => '/settings/activity-history',
                'permission' => 'manage_settings',
                'sort_order' => 16,
            ],
        ];

        foreach ($menus as $menu) {
            NavigationMenu::updateOrCreate(
                ['id' => $menu['id']],
                $menu
            );
        }
    }
}
